package com.workproofpay.backend.remittance.model;

public enum RemittancePolicyCode {
    RECIPIENT_NOT_ALLOWED,
    RECENT_RECIPIENT_CONFIRMATION_REQUIRED,
    HIGH_AMOUNT_CONFIRMATION_REQUIRED,
    SELF_TRANSFER_NOT_ALLOWED,
    INSUFFICIENT_WALLET_BALANCE,
    TRANSFER_ALREADY_IN_PROGRESS
}
