(function initMockupBoot(global) {
const mainTabs = ['home', 'workproof', 'send', 'transfer', 'manage', 'wage', 'vault'];

// Android migration map: Web tab ids -> Native route names + scope.
const architecture = Object.freeze({
    routes: Object.freeze({
        HOME: 'home',
        WORKPROOF: 'workproof',
        FINANCE: 'send',
        TRANSFER: 'transfer',
        ACCOUNT_MANAGE: 'manage',
        WAGE: 'wage',
        MENU: 'vault'
    }),
    scope: Object.freeze({
        p0: Object.freeze(['home', 'workproof', 'send', 'transfer', 'manage', 'wage', 'vault']),
        p1: Object.freeze(['advance', 'interest'])
    }),
    modules: Object.freeze({
        home: 'feature:home',
        workproof: 'feature:workproof',
        wage: 'feature:wage',
        send: 'feature:finance',
        transfer: 'feature:remittance',
        manage: 'feature:account-manage',
        vault: 'feature:menu'
    })
});

const translations = {
    ko: {
        doc_title: 'DonDone — Demo MVP',
        brand_tagline: '당신의 돈(Don), 처음부터 끝(Done)까지 던던하게.',
        greeting: '안녕하세요, Minh님',
        greeting_sub: '당신의 돈(Don), 처음부터 끝(Done)까지 던던하게.',
        asof_label: '기준일',
        demo_kicker: '데모 • 타임 트래블',
        home_account_kicker: '계좌',
        home_account_title: '내 계좌',
        home_selected_account: '선택 계좌',
        home_account_sub: '송금 전에 잔액과 수신자를 먼저 확인해볼까요?',
        home_sendable_label: '송금 가능',
        home_clock_title: '오늘 출퇴근',
        home_summary_kicker: '이번 달 정산',
        home_summary_title: '이번 달 돈 상태',
        home_summary_sub: '실입금과 참고용 추정을 비교해 현재 상태를 보여줍니다.',
        home_money_note: '급여 계산은 참고용 추정이며, 실제 지급/공제는 명세서 기준으로 달라질 수 있어요.',
        home_flow_kicker: '다음 행동',
        home_flow_title: '지금 해야 할 행동',
        home_quick_desc: '자주 쓰는 기능으로 바로 이동할 수 있어요.',
        cta_send_short: '송금',
        home_flow_workproof: '근무 일지',
        home_flow_wage: '차액 점검',
        home_flow_docs: '문서/신고 준비',
        home_flow_send: '송금',
        home_evidence_title: '근거 요약',
        home_evidence_sub: '상세 기록은 근무 탭에서 확인할 수 있어요.',
        home_proof_ids: '근거 ID',
        work_days: '근무일',
        days: '일',
        total_hours: '총 근무',
        hours: '시간',
        modified_records: '수정 기록',
        items: '건',
        wage_check: '급여 점검',
        cta_open_wage: '차액 보기',
        cta_open_docs: '문서',
        today_workproof: '오늘 근무 일지',
        cta_view_records: '기록 보기',
        cta_clock_in: '출근',
        cta_clock_out: '퇴근',
        location_snapshot: '위치 스냅샷 저장됨',
        timeline_title: '타임라인',
        view_all: '전체보기',
        tl_workproof_edit: '근무 기록 수정됨',
        tl_workproof_edit_desc: '수정 사유·첨부 유무·변경 전/후가 변경 기록으로 저장됩니다.',
        cta_go_workproof: '기록 확인',
        cta_fix: '수정',
        tl_wage_diff: '차이 확인',
        tl_wage_diff_desc: '참고용 추정과 실제 입금액을 비교해 확인이 필요한 차이와 근거를 보여줍니다.',
        cta_go_wage: '차액 화면',
        copilot_explain_short: '코파일럿',
        tl_docs_ready: 'Proof Pack PDF 준비됨',
        tl_docs_ready_desc: '월간 요약·근거·수정 이력·첨부 목록이 자동 포함됩니다.',
        cta_go_docs: '문서 보기',
        cta_make_claimkit_short: '준비',
        workproof_sub: '수정 가능하지만, 사유와 이력이 남아 신뢰를 높입니다.',
        workproof_title: '근무 일지',
        workproof_calendar_title: '근무 캘린더',
        workproof_calendar_sub: '기록 상태를 한 달 단위로 확인할 수 있어요.',
        workproof_calendar_count: '기록일',
        calendar_legend_none: '없음',
        calendar_legend_pending: '출근만',
        calendar_legend_done: '완료',
        calendar_legend_edited: '수정',
        calendar_status_none: '기록 없음',
        calendar_status_pending: '출근만 기록됨',
        calendar_status_done: '출퇴근 기록 완료',
        calendar_status_edited: '수정 기록 있음',
        workproof_day_title: '일자 상세',
        workproof_day_status_label: '상태',
        workproof_day_no_reason: '수정 사유 없음',
        workproof_day_no_record: '이 날짜에는 기록이 없습니다.',
        one_tap_kicker: '원탭',
        workproof_punch_title: '출퇴근 원탭 기록',
        workproof_punch_sub: '기록 시간 + 위치 스냅샷 1회 저장',
        record_time: '기록 시간',
        recent_records: '최근 기록',
        edit_reason_required: '수정 사유를 남겨주세요',
        audit_log: '변경 기록',
        audit_log_sub: '변경 이력은 보관되며 Proof Pack/근거 자료 묶음에 함께 포함돼요.',
        wage_sub: '근거 기반 급여 비교와 확인 흐름',
        wage_title: '급여 점검',
        copilot_explain: '이 화면 설명해줘',
        chip_why_diff: '왜 차액이 생겼어?',
        chip_evidence: '어떤 근거야?',
        chip_next: '다음 행동은?',
        wage_action_sequence: '추천 경로(선택)',
        wage_primary_kicker: '다음 추천 행동',
        wage_primary_hint: '현재 상태 기준 추천이며, 다른 경로를 선택할 수 있어요.',
        wage_more_actions: '다른 액션 보기',
        wage_hide_actions: '액션 접기',
        wage_step_word: '단계',
        wage_step_proofpack: 'Proof Pack',
        wage_step_message: '메시지 초안',
        wage_step_claimkit: '근거 자료 묶음',
        wage_step_instantclaim: '신고 준비',
        wage_disclaimer_1: '이 급여 계산은 참고용 추정입니다. 실제 지급/공제는 근로계약, 급여명세서, 회사 규정에 따라 달라질 수 있습니다.',
        wage_disclaimer_2: '공제 항목을 입력하지 않아 공제가 반영되지 않았습니다.(공제 미반영)',
        wage_overview: '월간 요약',
        modified_badge: '수정',
        evidence_ready: '근거 준비',
        overtime_night: '연장/야간',
        estimate_title: '참고용 추정 급여',
        evidence_based: '근거 자료(WorkProof) 기반',
        base: '기본',
        overtime_premium: '연장 프리미엄',
        night_premium: '야간 프리미엄',
        estimated_total: '추정 합계',
        actual_deposit: '실제 입금액(실수령)',
        apply: '적용',
        deduction_unknown: '공제 미반영',
        threshold_relaxed: '임계값 완화 적용',
        estimated: '추정',
        actual: '실제',
        difference: '차액',
        possible_causes: '함께 확인된 근거',
        cause_ot: '연장 12h · 야간 6h 포함',
        cause_modified: '수정 기록 2건(사유/첨부 포함)',
        cause_workproof_ids: '근거 자료 ID 18건 연결',
        cta_make_proofpack: 'Proof Pack',
        cta_make_proofpack_short: 'Proof',
        cta_draft_message: '메시지 초안',
        cta_draft_message_short: '메시지',
        cta_make_claimkit: '근거 자료 묶음 보기',
        cta_instant_claim: '신고 준비 보기',
        cta_instant_claim_short: '준비',
        cta_open_send: '송금으로 이동',
        claim_disclaimer: '이 안내는 참고용이며 법률 자문이 아닙니다. 필요하면 전문기관 상담을 이용해 주세요.',
        remittance_title: '금융',
        remittance_sub: '계좌 현황을 확인한 뒤 송금·미리받기·이자를 관리할 수 있어요.',
        finance_send_title: '내 계좌',
        finance_account_balance_label: '선택 계좌 잔액',
        finance_change_account: '계좌 관리',
        home_transfer_path_hint: '계좌를 먼저 확인한 뒤 송금을 시작해볼까요?',
        transfer_form_title: '송금',
        transfer_form_sub: '계좌를 확인한 뒤 수신자와 금액을 입력해 주세요.',
        transfer_from_account: '보내는 계좌',
        transfer_to_recipient: '받는 사람',
        transfer_step_recipient_title: '받는 사람 선택',
        transfer_step_recipient_sub: '받는 사람을 선택해 주세요.',
        transfer_step_amount_title: '금액 입력',
        transfer_step_amount_sub: '보내는 계좌·받는 사람·금액을 함께 확인해 주세요.',
        transfer_step_account_title: '계좌 선택',
        transfer_step_account_sub: '보낼 계좌를 선택해 주세요.',
        transfer_select_hint: '수신자를 선택하면 금액 입력 화면으로 이동합니다.',
        transfer_change_recipient: '변경',
        transfer_change_account: '변경',
        transfer_manage_wallets: '지갑 관리',
        transfer_account_picker_sub: '출금할 계좌를 선택해 주세요.',
        transfer_open_cta: '송금하기',
        finance_wage_kicker: '급여 점검',
        finance_wage_title: '급여 점검 요약',
        finance_wage_sub: '상세 내용은 급여 점검에서 확인할 수 있어요.',
        finance_go_wage: '급여 점검',
        finance_interest_kicker: '예치 이자',
        finance_interest_title: '예치 이자',
        finance_interest_desc: '예치 잔액과 누적 이자를 금융에서 바로 확인합니다.',
        finance_interest_open: '상세',
        finance_interest_open_apply: '신청',
        finance_advance_kicker: '미리받기',
        finance_advance_title: '미리받기',
        finance_advance_desc: '근무 기록 기준 한도로 급여일 전에 일부를 미리 받습니다.',
        finance_advance_open: '자세히',
        advance_card_reflected: '근무 반영',
        advance_verified_label: '확인 근무',
        advance_formula_prefix: '한도 계산',
        advance_available_label: '지금 가능 금액',
        advance_repay_label: '상환 예정',
        advance_cta_request: '미리받기 신청',
        advance_limit_note: '한도: 확인된 근무분의 20% · 최대 ₩500,000',
        advance_sheet_sub: '근무 기록 기반 한도로 급여일 전에 일부를 먼저 받습니다.',
        advance_calendar_basis_title: '근무 캘린더 반영 현황',
        advance_updated_label: '반영 기준',
        advance_review_label: '확인 필요',
        advance_unreflected_label: '미반영',
        advance_used_label: '누적 사용',
        advance_receive_label: '이번 수령 가능',
        advance_fee_label: '수수료',
        advance_workproof_summary: '근무 근거 요약',
        advance_verified_days_label: '확인 근무일',
        advance_verified_hours_label: '확인 근무시간',
        advance_verified_wage_label: '환산 근무분',
        advance_limit_breakdown_title: '한도 계산 근거',
        advance_limit_base_label: '기본 한도(근무분×20%)',
        advance_limit_bonus_label: '상환 보너스',
        advance_limit_final_label: '최종 한도',
        advance_request_amount_title: '받을 금액 선택',
        advance_history_title: '이번 달 미리받기 이력',
        advance_tier_label: '한도 단계',
        advance_history_empty: '이력이 없습니다.',
        allow_list: '허용 목록',
        recipient_title: '수신자 선택',
        verified_only: '등록된 수신자만',
        selected_recipient: '선택된 수신자',
        send_amount: '보낼 금액',
        testnet: '데모',
        cta_send: '보내기',
        send_confirm_title: '송금 전 확인',
        send_confirm_sub: '허용 목록/금액/정책 확인 후 전송합니다.',
        send_confirm_recipient: '받는 분',
        send_confirm_address: '지갑 주소',
        send_confirm_amount: '보낼 금액',
        send_confirm_check_allow: '허용 목록 수신자만 전송 가능',
        send_confirm_check_testnet: '데모 송금(실자금 이동 없음)',
        send_confirm_cta: '확인 후 보내기',
        testnet_disclaimer: '현재는 데모 환경입니다. 실제 자금 이동이 발생하지 않습니다.',
        vault_title: '자산',
        vault_sub: '자산·이자 현황 + 문서 보관',
        vault_sim_kicker: '미리받기 시뮬레이션',
        vault_sim_title: '이자 현황',
        vault_sim_desc: 'MVP 범위 밖 기능은 데모 수치로만 보여줍니다.',
        vault_limit: '가용 한도',
        vault_used: '사용 금액',
        vault_interest: '누적 이자(추정)',
        vault_repay: '상환 예상',
        vault_rate: '연 이율',
        vault_elapsed_days: '경과 일수',
        vault_demo_note: '미리받기/이자는 데모 시뮬레이션입니다.',
        vault_status_active: '이자 누적 중',
        vault_status_idle: '미사용',
        menu_title: '메뉴',
        menu_sub: '서비스와 문서를 한곳에서 관리할 수 있어요.',
        menu_services_title: '서비스',
        menu_services_desc: '급여 점검, 신고 준비, 계좌 관리를 여기서 이용할 수 있어요.',
        menu_go_wage: '급여 점검',
        menu_go_interest: '예치 이자',
        menu_go_message: '메시지 초안',
        menu_go_claim: '신고 준비',
        menu_go_account_manage: '계좌·지갑 관리',
        menu_go_settings: '설정',
        account_manage_title: '계좌·지갑 관리',
        account_manage_sub: '송금에 쓸 계좌와 수신 지갑을 등록하고 관리할 수 있어요.',
        account_manage_accounts: '내 계좌',
        account_manage_wallets: '수신 지갑',
        account_manage_add_account: '계좌 추가',
        account_manage_add_wallet: '지갑 추가',
        interest_kicker: '예치 이자',
        interest_title: '예치 이자',
        interest_sub: '스테이블 코인 예치 기준 예상 이자 현황입니다.',
        interest_status_not_enrolled: '아직 예치를 시작하지 않았어요.',
        interest_status_enrolled: '예치가 활성화되어 이자가 적립 중이에요.',
        interest_status_apply_hint: '예치 신청 후 이자 예상과 수익 구성을 확인할 수 있어요.',
        interest_not_enrolled_short: '미신청',
        interest_apply_available_label: '지금 예치 가능한 금액',
        interest_apply_amount_title: '예치 신청 금액',
        interest_apply_expected_monthly: '월 예상 이자',
        interest_apply_expected_daily: '일 예상 이자',
        interest_apply_note: '예치금은 Vault 풀에 들어가며, DeFi 운용 수익 + 가불 수수료 기여분으로 이자가 적립됩니다.',
        interest_apply_cta: '예치 시작하기',
        interest_balance_label: '예치 잔액',
        interest_apr_label: '예상 연이율',
        interest_accrued_label: '누적 이자(추정)',
        interest_monthly_label: '월 예상 이자',
        interest_daily_label: '일 예상 이자',
        interest_breakdown_short: '월 수익',
        interest_fee_short: '가불수수료',
        interest_breakdown_title: '월 수익 구성(추정)',
        interest_defi_label: 'DeFi 운용 수익',
        interest_fee_share_label: '가불 수수료 기여분',
        interest_total_monthly_label: '합계',
        interest_pool_title: '풀 운용 현황',
        interest_pool_defi_ratio: 'DeFi 운용 비율',
        interest_pool_advance_ratio: '가불 풀 비율',
        interest_pool_used_label: '가불 풀 사용률',
        interest_disclaimer: '이자 수치는 데모용 추정값이며 실제 수익을 보장하지 않습니다.',
        docs_title: '문서',
        docs_sub: 'Proof Pack · 근거 자료 묶음 · 송금 영수증 PDF',
        transfer_status: '송금 상태',
        transfer_submitted: '전송 요청됨',
        transfer_confirmed: '확정됨',
        tx_hash: '전송 해시',
        copilot_disclaimer: '이 안내는 화면에 표시된 사실을 바탕으로 작성된 참고 문장입니다.',
        draft_kicker: '메시지 초안',
        draft_title: '사업주 메시지 초안',
        draft_sub: '근거를 포함해 정중하지만 단호하게',
        copy: '복사',
        close: '닫기',
        instant_claim_title: '신고 준비',
        instant_claim_sub: '자동 제출이 아니라, 제출을 쉽게 만드는 반자동 지원',
        claim_summary_label: '제출용 요약 문장',
        claim_make_sentence: '제출용 문장 만들어줘',
        chip_firm: '정중하지만 단호하게 써줘',
        chip_short: '짧게 요약해줘',
        claim_files_title: '파일',
        cta_open_docs_tab: '문서로 이동',
        doc_proofpack: 'Proof Pack',
        doc_claimkit: '근거 자료 묶음',
        cta_open: '열기',
        cta_generate: '만들기',
        cta_generating: '생성 중',
        claim_paths_title: '접수 경로 안내',
        cta_shortcut: '바로가기',
        path_online_title: '온라인',
        path_online_desc: '온라인 접수에 필요한 항목을 안내합니다.',
        path_phone_title: '전화',
        path_phone_desc: '상담/접수 전에 준비할 내용을 안내합니다.',
        path_visit_title: '방문',
        path_visit_desc: '방문 접수용 체크리스트를 안내합니다.',
        checklist_title: '체크리스트',
        check_proofpack: 'Proof Pack 준비',
        check_claimkit: '근거 자료 묶음 준비',
        check_path: '접수 경로 확인(온라인/전화/방문)',
        open_claimkit: '근거 자료 묶음 열기',
        back_to_wage: '차액 화면',
        edit_title: '근무 시간 수정',
        edit_reason: '수정 사유',
        edit_reason_pick: '선택하세요',
        reason_1: '출근/퇴근 탭을 늦게 눌렀어요',
        reason_2: '연장근무가 있었어요',
        reason_3: '휴게시간이 달랐어요',
        reason_4: '기록이 누락됐어요',
        reason_5: '기타(직접 입력)',
        attachments: '추가 증거(선택)',
        attachments_desc: '사진/메모 첨부 가능 · 첨부 없음도 기록됩니다.',
        save: '저장',
        settings_title: '설정',
        language_title: '언어',
        language_desc: '앱 표시 언어를 선택해 주세요.',
        language_ko: '한국어',
        language_en: 'English',
        demo_mode: '데모 모드(Time Travel)',
        demo_mode_desc: '발표용: 기준일을 바꿔 한 달 여정을 압축합니다.',
        status_ready: '준비됨',
        status_in_progress: '진행 중',
        status_done: '완료',
        flow_status_ready: '준비됨',
        flow_status_progress: '진행 중',
        flow_status_done: '완료',
        flow_status_alert: '확인 필요',
        flow_status_blocked: '조건 확인',
        home_next_make_proofpack: '먼저 Proof Pack으로 근거를 정리해볼까요?',
        home_next_open_message: '메시지 초안으로 먼저 확인 요청을 해볼까요?',
        home_next_make_claimkit: '혹시 근거 자료 묶음이 필요하신가요?',
        home_next_open_instant: '신고 준비 화면에서 제출용 문장을 확인해볼까요?',
        home_next_send_ready: '허용 목록 수신자에게 송금을 진행할 수 있어요. 지금 시작해볼까요?',
        home_next_no_anomaly: '현재는 확인이 필요한 차이가 크지 않아 문서/송금 흐름으로 이동할 수 있어요.',
        home_next_done: '흐름이 완료되었습니다. 필요하면 영수증/문서를 다시 확인해볼 수 있어요.',
        badge_edited: '수정됨',
        badge_log: '기록',
        badge_attach: '첨부',
        badge_attach_none: '첨부 없음',
        badge_location: '위치',
        label_in: '출근',
        label_out: '퇴근',
        label_reason: '사유:',
        cta_edit: '수정',
        doc_status_ready: '준비됨',
        doc_status_queued: '대기 중',
        doc_status_not_yet: '미생성',
        cta_share: '공유',
        cta_download: '다운로드',
        diff_anomaly_kicker: '차이 확인',
        diff_ok_kicker: '이상 없음',
        diff_anomaly_title: '확인 필요한 차이',
        diff_ok_title: '이상 없음',
        diff_anomaly_desc: '예상과 실제 사이에 확인이 필요한 차이가 보여요. 근거를 함께 확인해볼까요?',
        diff_ok_desc: '현재 입력 기준에서는 확인이 필요한 차이가 크지 않아요.',
        transfer_waiting: '확정 대기 중',
        transfer_not_confirmed: '아직 확정되지 않음',
        transfer_submitted_to_network: '네트워크에 전송됨',
        transfer_confirming: '확정 확인 중...',
        transfer_confirmed_sub: '확정 완료',
        toast_copied: '복사 완료',
        toast_link_copied: '링크가 복사됐어요',
        toast_generated: '생성 완료',
        toast_generating_doc: '문서 생성 중...',
        toast_enter_amount: '보낼 금액을 입력해 주세요.',
        toast_insufficient_balance: '선택한 계좌 잔액이 부족해요.',
        toast_account_added: '계좌가 추가되었어요.',
        toast_wallet_added: '수신 지갑이 추가되었어요.',
        toast_advance_done: '미리받기 신청이 접수되었습니다.',
        toast_interest_applied: '예치 신청이 완료되었습니다.',
        nav_home: '홈',
        nav_workproof: '근무',
        nav_send: '금융',
        nav_wage: '급여',
        nav_docs: '문서',
        nav_vault: '메뉴'
    },
    en: {
        doc_title: 'DonDone — Demo MVP',
        brand_tagline: 'Your Don, from start to done.',
        greeting: 'Hello, Minh',
        greeting_sub: 'Your Don, from start to done.',
        asof_label: 'As of',
        demo_kicker: 'DEMO • TIME TRAVEL',
        home_account_kicker: 'ACCOUNT',
        home_account_title: 'My Account',
        home_selected_account: 'Selected account',
        home_account_sub: 'You can check balance and recipient before transfer.',
        home_sendable_label: 'Sendable',
        home_clock_title: 'Today clock in/out',
        home_summary_kicker: 'MONEY OVERVIEW',
        home_summary_title: 'Money status this month',
        home_summary_sub: 'Compare your actual deposit with the reference estimate.',
        home_money_note: 'Wage numbers are reference estimates. Actual pay and deductions follow your payslip.',
        home_flow_kicker: 'NEXT ACTION',
        home_flow_title: 'What to do now',
        home_quick_desc: 'Jump to features you use often.',
        cta_send_short: 'Send',
        home_flow_workproof: 'Work evidence',
        home_flow_wage: 'Wage check',
        home_flow_docs: 'Docs / claim prep',
        home_flow_send: 'Remittance',
        home_evidence_title: 'Evidence summary',
        home_evidence_sub: 'Open the Work tab for full logs and edits.',
        home_proof_ids: 'Evidence IDs',
        work_days: 'Work days',
        days: 'days',
        total_hours: 'Total',
        hours: 'hrs',
        modified_records: 'Edits',
        items: 'items',
        wage_check: 'Wage check',
        cta_open_wage: 'View diff',
        cta_open_docs: 'Docs',
        today_workproof: 'Today WorkProof',
        cta_view_records: 'View logs',
        cta_clock_in: 'Clock in',
        cta_clock_out: 'Clock out',
        location_snapshot: 'Location snapshot saved',
        timeline_title: 'Timeline',
        view_all: 'View all',
        tl_workproof_edit: 'Work log edited',
        tl_workproof_edit_desc: 'Reason, attachments, and before/after are stored in change history.',
        cta_go_workproof: 'Open logs',
        cta_fix: 'Edit',
        tl_wage_diff: 'Review difference',
        tl_wage_diff_desc: 'Compares estimate vs actual deposit and highlights review points with evidence.',
        cta_go_wage: 'Open diff',
        copilot_explain_short: 'Copilot',
        tl_docs_ready: 'Proof Pack ready',
        tl_docs_ready_desc: 'Summary, evidence, change history, and attachments are included.',
        cta_go_docs: 'Open docs',
        cta_make_claimkit_short: 'Claim Kit',
        workproof_sub: 'Editable, but always explained with change history.',
        workproof_title: 'WorkProof',
        workproof_calendar_title: 'Work calendar',
        workproof_calendar_sub: 'Review your logging status month by month.',
        workproof_calendar_count: 'Logged days',
        calendar_legend_none: 'None',
        calendar_legend_pending: 'Clock-in only',
        calendar_legend_done: 'Completed',
        calendar_legend_edited: 'Edited',
        calendar_status_none: 'No record',
        calendar_status_pending: 'Only clock-in was recorded',
        calendar_status_done: 'Clock-in/out completed',
        calendar_status_edited: 'Edited record exists',
        workproof_day_title: 'Day details',
        workproof_day_status_label: 'Status',
        workproof_day_no_reason: 'No edit reason',
        workproof_day_no_record: 'No record for this date.',
        one_tap_kicker: 'ONE TAP',
        workproof_punch_title: 'One-tap clock in/out',
        workproof_punch_sub: 'Recorded time + one-time location snapshot',
        record_time: 'Recorded',
        recent_records: 'Recent logs',
        edit_reason_required: 'Add a reason',
        audit_log: 'Change history',
        audit_log_sub: 'Change history is retained and included in claim documents.',
        wage_sub: 'Evidence-based wage review flow',
        wage_title: 'Wage Shield',
        copilot_explain: 'Explain this screen',
        chip_why_diff: 'Why is there a diff?',
        chip_evidence: 'What evidence?',
        chip_next: 'Next steps?',
        wage_action_sequence: 'Suggested paths',
        wage_primary_kicker: 'Suggested next step',
        wage_primary_hint: 'This is a recommendation based on current records. You can choose another path.',
        wage_more_actions: 'More actions',
        wage_hide_actions: 'Hide actions',
        wage_step_word: 'STEP',
        wage_step_proofpack: 'Proof Pack',
        wage_step_message: 'Message draft',
        wage_step_claimkit: 'Claim Kit',
        wage_step_instantclaim: 'Instant claim',
        wage_disclaimer_1: 'This wage estimate is for reference. Actual pay/deductions may differ by contract and payslip.',
        wage_disclaimer_2: 'Deductions are not reflected (not provided).',
        wage_overview: 'Monthly overview',
        modified_badge: 'Edits',
        evidence_ready: 'Evidence ready',
        overtime_night: 'OT/Night',
        estimate_title: 'Reference estimate',
        evidence_based: 'Based on WorkProof',
        base: 'Base',
        overtime_premium: 'OT premium',
        night_premium: 'Night premium',
        estimated_total: 'Estimated total',
        actual_deposit: 'Actual deposit',
        apply: 'Apply',
        deduction_unknown: 'No deductions',
        threshold_relaxed: 'Relaxed threshold',
        estimated: 'Estimated',
        actual: 'Actual',
        difference: 'Difference',
        possible_causes: 'Evidence to review',
        cause_ot: 'Includes OT 12h · Night 6h',
        cause_modified: '2 edited logs (reason/attachments)',
        cause_workproof_ids: 'Linked to 18 WorkProof IDs',
        cta_make_proofpack: 'Proof Pack',
        cta_make_proofpack_short: 'Proof',
        cta_draft_message: 'Message draft',
        cta_draft_message_short: 'Message',
        cta_make_claimkit: 'Open Claim Kit',
        cta_instant_claim: 'Open claim prep',
        cta_instant_claim_short: 'Prep',
        cta_open_send: 'Go to send',
        claim_disclaimer: 'This guidance is for reference and is not legal advice.',
        remittance_title: 'Finance',
        remittance_sub: 'Review accounts first, then manage transfer, advance, and yield.',
        finance_send_title: 'My accounts',
        finance_account_balance_label: 'Selected account balance',
        finance_change_account: 'Manage account',
        home_transfer_path_hint: 'Review your account first, then start transfer.',
        transfer_form_title: 'Transfer',
        transfer_form_sub: 'Review account first, then set recipient and amount.',
        transfer_from_account: 'From account',
        transfer_to_recipient: 'Recipient',
        transfer_step_recipient_title: 'Choose recipient',
        transfer_step_recipient_sub: 'Select the recipient.',
        transfer_step_amount_title: 'Enter amount',
        transfer_step_amount_sub: 'Confirm account, recipient, and amount.',
        transfer_step_account_title: 'Choose account',
        transfer_step_account_sub: 'Select the account to send from.',
        transfer_select_hint: 'Selecting a recipient moves you to amount entry.',
        transfer_change_recipient: 'Change',
        transfer_change_account: 'Change',
        transfer_manage_wallets: 'Manage',
        transfer_account_picker_sub: 'Choose the account to send from.',
        transfer_open_cta: 'Start transfer',
        finance_wage_kicker: 'WAGE CHECK',
        finance_wage_title: 'Wage check summary',
        finance_wage_sub: 'Open wage check if you want full details.',
        finance_go_wage: 'Open wage check',
        finance_interest_kicker: 'VAULT YIELD',
        finance_interest_title: 'Yield overview',
        finance_interest_desc: 'See vault balance and accrued yield right in Finance.',
        finance_interest_open: 'Details',
        finance_interest_open_apply: 'Apply',
        finance_advance_kicker: 'PAYCHECK ADVANCE',
        finance_advance_title: 'Paycheck advance',
        finance_advance_desc: 'Receive part of your pay before payday within your work-based limit.',
        finance_advance_open: 'Details',
        advance_card_reflected: 'Work reflected',
        advance_verified_label: 'Verified work',
        advance_formula_prefix: 'Limit formula',
        advance_available_label: 'Available now',
        advance_repay_label: 'Repay date',
        advance_cta_request: 'Request advance',
        advance_limit_note: 'Limit: 20% of verified work, capped at ₩500,000',
        advance_sheet_sub: 'Advance is based on verified work and repaid on payday.',
        advance_calendar_basis_title: 'Calendar-based eligibility',
        advance_updated_label: 'As of',
        advance_review_label: 'Review needed',
        advance_unreflected_label: 'Not reflected',
        advance_used_label: 'Used so far',
        advance_receive_label: 'Available payout',
        advance_fee_label: 'Service fee',
        advance_workproof_summary: 'WorkProof basis',
        advance_verified_days_label: 'Verified days',
        advance_verified_hours_label: 'Verified hours',
        advance_verified_wage_label: 'Converted wage base',
        advance_limit_breakdown_title: 'Limit breakdown',
        advance_limit_base_label: 'Base limit (20% of verified work)',
        advance_limit_bonus_label: 'Repayment bonus',
        advance_limit_final_label: 'Final limit',
        advance_request_amount_title: 'Select amount',
        advance_history_title: 'This month advance history',
        advance_tier_label: 'Tier',
        advance_history_empty: 'No history yet.',
        allow_list: 'Allow list',
        recipient_title: 'Choose recipient',
        verified_only: 'Allow list only',
        selected_recipient: 'Selected',
        send_amount: 'Amount',
        testnet: 'DEMO',
        cta_send: 'Send',
        send_confirm_title: 'Confirm before transfer',
        send_confirm_sub: 'Review allow-list recipient, amount, and policy checks.',
        send_confirm_recipient: 'Recipient',
        send_confirm_address: 'Wallet address',
        send_confirm_amount: 'Amount',
        send_confirm_check_allow: 'Only allow-list recipients can receive transfers',
        send_confirm_check_testnet: 'Demo transfer (no real funds moved)',
        send_confirm_cta: 'Confirm and send',
        testnet_disclaimer: 'This is a demo environment. No real funds are moved.',
        vault_title: 'Vault',
        vault_sub: 'Advance/interest demo + document storage',
        vault_sim_kicker: 'ADVANCE SIMULATION',
        vault_sim_title: 'Interest status',
        vault_sim_desc: 'Out-of-scope MVP feature shown as demo-only numbers.',
        vault_limit: 'Available limit',
        vault_used: 'Used amount',
        vault_interest: 'Accrued interest (est.)',
        vault_repay: 'Expected repayment',
        vault_rate: 'APR',
        vault_elapsed_days: 'Elapsed days',
        vault_demo_note: 'Advance/interest is demo simulation only.',
        vault_status_active: 'Interest accruing',
        vault_status_idle: 'Not used',
        menu_title: 'Menu',
        menu_sub: 'Services and documents are managed in one place.',
        menu_services_title: 'Services',
        menu_services_desc: 'Wage check, claim prep, and account management are available here.',
        menu_go_wage: 'Wage check',
        menu_go_interest: 'Yield details',
        menu_go_message: 'Message draft',
        menu_go_claim: 'Instant claim',
        menu_go_account_manage: 'Account/Wallet',
        menu_go_settings: 'Settings',
        account_manage_title: 'Account & wallet',
        account_manage_sub: 'Register and manage source accounts and recipient wallets in one place.',
        account_manage_accounts: 'My accounts',
        account_manage_wallets: 'Recipient wallets',
        account_manage_add_account: 'Add account',
        account_manage_add_wallet: 'Add wallet',
        interest_kicker: 'VAULT YIELD',
        interest_title: 'Yield details',
        interest_sub: 'Estimated yield for your stablecoin vault.',
        interest_status_not_enrolled: 'You have not started vault deposit yet.',
        interest_status_enrolled: 'Vault deposit is active and yield is accruing.',
        interest_status_apply_hint: 'Apply first to see expected yield and breakdown.',
        interest_not_enrolled_short: 'Not started',
        interest_apply_available_label: 'Available to deposit now',
        interest_apply_amount_title: 'Deposit request amount',
        interest_apply_expected_monthly: 'Expected monthly yield',
        interest_apply_expected_daily: 'Expected daily yield',
        interest_apply_note: 'Your deposit enters the Vault pool, and yield comes from DeFi returns plus advance-fee contribution.',
        interest_apply_cta: 'Start deposit',
        interest_balance_label: 'Vault balance',
        interest_apr_label: 'Estimated APR',
        interest_accrued_label: 'Accrued yield (est.)',
        interest_monthly_label: 'Monthly estimate',
        interest_daily_label: 'Daily estimate',
        interest_breakdown_short: 'Monthly mix',
        interest_fee_short: 'Advance fee',
        interest_breakdown_title: 'Monthly yield breakdown (est.)',
        interest_defi_label: 'DeFi yield',
        interest_fee_share_label: 'Advance fee contribution',
        interest_total_monthly_label: 'Total',
        interest_pool_title: 'Pool allocation',
        interest_pool_defi_ratio: 'DeFi allocation',
        interest_pool_advance_ratio: 'Advance pool allocation',
        interest_pool_used_label: 'Advance pool utilization',
        interest_disclaimer: 'Yield values are demo estimates and not guaranteed.',
        docs_title: 'Documents',
        docs_sub: 'Proof Pack · Claim Kit · Transfer receipt PDF',
        transfer_status: 'Transfer status',
        transfer_submitted: 'SUBMITTED',
        transfer_confirmed: 'CONFIRMED',
        tx_hash: 'TX HASH',
        copilot_disclaimer: 'This text is generated from on-screen facts.',
        draft_kicker: 'MESSAGE DRAFT',
        draft_title: 'Employer message draft',
        draft_sub: 'Polite but firm, with evidence',
        copy: 'Copy',
        close: 'Close',
        instant_claim_title: 'Instant claim',
        instant_claim_sub: 'Semi-automated preparation, not auto filing',
        claim_summary_label: 'Summary sentence',
        claim_make_sentence: 'Generate a submission sentence',
        chip_firm: 'Polite but firm',
        chip_short: 'Summarize briefly',
        claim_files_title: 'Files',
        cta_open_docs_tab: 'Open Docs',
        doc_proofpack: 'Proof Pack',
        doc_claimkit: 'Claim Kit',
        cta_open: 'Open',
        cta_generate: 'Generate',
        cta_generating: 'Generating...',
        claim_paths_title: 'Submission paths',
        cta_shortcut: 'Shortcut',
        path_online_title: 'Online',
        path_online_desc: 'Guidance for online submission (demo).',
        path_phone_title: 'Phone',
        path_phone_desc: 'What to prepare before calling (demo).',
        path_visit_title: 'Visit',
        path_visit_desc: 'Checklist for in-person visit (demo).',
        checklist_title: 'Checklist',
        check_proofpack: 'Proof Pack ready',
        check_claimkit: 'Claim Kit ready',
        check_path: 'Confirm submission path',
        open_claimkit: 'Open Claim Kit',
        back_to_wage: 'Back to diff',
        edit_title: 'Edit work log',
        edit_reason: 'Reason',
        edit_reason_pick: 'Pick one',
        reason_1: 'I tapped late',
        reason_2: 'There was overtime',
        reason_3: 'Break time differed',
        reason_4: 'A log was missing',
        reason_5: 'Other',
        attachments: 'Extra evidence (optional)',
        attachments_desc: 'Photo/memo optional · recorded even when none',
        save: 'Save',
        settings_title: 'Settings',
        language_title: 'Language',
        language_desc: 'Choose display language.',
        language_ko: 'Korean',
        language_en: 'English',
        demo_mode: 'Demo mode (Time Travel)',
        demo_mode_desc: 'For presentations only.',
        status_ready: 'READY',
        status_in_progress: 'IN PROGRESS',
        status_done: 'DONE',
        flow_status_ready: 'READY',
        flow_status_progress: 'IN PROGRESS',
        flow_status_done: 'DONE',
        flow_status_alert: 'CHECK',
        flow_status_blocked: 'REVIEW',
        home_next_make_proofpack: 'Would you like to organize evidence with Proof Pack first?',
        home_next_open_message: 'Would you like to start with a message draft?',
        home_next_make_claimkit: 'Would you like to prepare a Claim Kit now?',
        home_next_open_instant: 'Would you like to review the submission sentence in claim prep?',
        home_next_send_ready: 'You can transfer to an allow-list recipient when ready.',
        home_next_no_anomaly: 'No anomaly now; you can move to docs/remittance flow.',
        home_next_done: 'Flow complete. You can review receipts/documents anytime.',
        badge_edited: 'Edited',
        badge_log: 'Log',
        badge_attach: 'Attachments',
        badge_attach_none: 'No attachments',
        badge_location: 'Location',
        label_in: 'IN',
        label_out: 'OUT',
        label_reason: 'Reason:',
        cta_edit: 'Edit',
        doc_status_ready: 'READY',
        doc_status_queued: 'QUEUED',
        doc_status_not_yet: 'NOT YET',
        cta_share: 'Share',
        cta_download: 'Download',
        diff_anomaly_kicker: 'REVIEW DIFF',
        diff_ok_kicker: 'NO ANOMALY',
        diff_anomaly_title: 'Difference to review',
        diff_ok_title: 'No anomaly',
        diff_anomaly_desc: 'There seems to be a difference between estimate and actual deposit. Want to review evidence first?',
        diff_ok_desc: 'No clear anomaly based on current inputs.',
        transfer_waiting: 'Waiting for confirmation',
        transfer_not_confirmed: 'Not confirmed yet',
        transfer_submitted_to_network: 'Submitted to network',
        transfer_confirming: 'Confirming...',
        transfer_confirmed_sub: 'Confirmed',
        toast_copied: 'Copied',
        toast_link_copied: 'Link copied',
        toast_generated: 'Generated',
        toast_generating_doc: 'Generating document...',
        toast_enter_amount: 'Please enter an amount.',
        toast_insufficient_balance: 'Insufficient balance in the selected account.',
        toast_account_added: 'Account added.',
        toast_wallet_added: 'Recipient wallet added.',
        toast_advance_done: 'Advance request submitted.',
        toast_interest_applied: 'Vault deposit request submitted.',
        nav_home: 'Home',
        nav_workproof: 'Work',
        nav_send: 'Finance',
        nav_wage: 'Wage',
        nav_docs: 'Docs',
        nav_vault: 'Menu'
    }
};
function createInitialState() {
    return {
    demo: {
        year: 2026,
        month: 3,
        asOfDay: 28,
        enabled: true,
        autoplay: false,
        autoplayTimer: null
    },
    workproof: {
        workplaceName: 'Green Farm',
        workplaceAddress: '',
        today: { clockIn: null, clockOut: null },
        calendarOffset: 0,
        selectedCalendarDay: null,
        records: [
            { id: 'WP-0327-01', day: 27, inTime: '09:01', outTime: '18:03', modified: false, reasonKey: null, reasonMemo: null, attachments: 0 },
            { id: 'WP-0326-01', day: 26, inTime: '09:05', outTime: '18:15', modified: false, reasonKey: null, reasonMemo: null, attachments: 0 },
            { id: 'WP-0318-01', day: 18, inTime: '09:10', outTime: '18:10', modified: true, reasonKey: 'reason_1', reasonMemo: null, attachments: 1 }
        ],
        audit: [
            { id: 'WP-0318-01', before: '08:57–18:10', after: '09:10–18:10', reasonKey: 'reason_1', reasonMemo: null, attachments: 1, at: '2026-03-18 20:11' }
        ]
    },
    wage: {
        workDays: 18,
        totalHours: 142,
        overtimeHours: 12,
        nightHours: 6,
        hourly: 12000,
        deductionsKnown: false,
        actualDeposit: 1740000,
        showSecondaryActions: false
    },
    remittance: {
        accounts: [
            { id: 'A-001', name: '주 계좌', number: '****-3124', balance: 1740000 },
            { id: 'A-002', name: '생활비 계좌', number: '****-8271', balance: 620000 }
        ],
        selectedAccountId: 'A-001',
        recipients: [],
        selectedRecipientId: null,
        flowStep: 'RECIPIENT',
        draftAmount: 50,
        txHash: '0x9f2e3d8b1c0a4e7f6d5c4b3a20e1f0d9c8b7a6f5e4d3c2b1a0...',
        status: 'IDLE'
    },
    advance: {
        maxCap: 500000,
        limitRate: 0.2,
        used: 120000,
        flatFee: 1500,
        selectedRequest: 100000,
        previousRepaymentGood: true,
        bonusLimit: 100000,
        history: [
            { id: 'ADV-0321-01', date: '2026-03-21', amount: 100000, fee: 1500, status: '상환 예정' },
            { id: 'ADV-0312-01', date: '2026-03-12', amount: 200000, fee: 1500, status: '상환 완료' }
        ]
    },
    vault: {
        enabled: false,
        selectedApplyAmount: 300000,
        applyOptions: [100000, 300000, 500000, 1000000],
        userDeposit: 0,
        apr: 0.043,
        accruedInterest: 0,
        totalPool: 42000000,
        defiRatio: 0.7,
        advanceRatio: 0.3,
        advanceUtilization: 0.42,
        monthlyFeeRevenue: 285000
    },
    docs: [
        { id: 'DOC-PROOF-2026-03', type: 'PROOF_PACK', month: '2026-03', status: 'READY', updatedAt: '2026-03-28 14:21' },
        { id: 'DOC-CLAIM-2026-03', type: 'CLAIM_KIT', month: '2026-03', status: 'NOT_CREATED', updatedAt: null },
        { id: 'DOC-RECEIPT-0007', type: 'TRANSFER_RECEIPT', receiptNo: '0007', status: 'READY', updatedAt: '2026-03-19 09:12' }
    ],
    editing: { recordId: null },
    claim: {
        summaryStyle: 'default',
        instantClaimOpened: false
    },
    ui: {
        currentTab: 'home',
        transferReturnTab: 'send',
        manageReturnTab: 'send',
        accountSeq: 3,
        recipientSeq: 1,
        auth: {
            loggedIn: false
        },
        onboarding: {
            completed: false,
            step: 1,
            mapVerified: false,
            wageUnit: 'hourly'
        }
    }
    };
}

global.MockupBoot = Object.freeze({
    mainTabs,
    translations,
    createInitialState,
    architecture
});
})(window);
