CREATE TABLE IF NOT EXISTS advance_policies (
    advance_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    payday_day INTEGER NOT NULL,
    same_day_advance_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    reduced_cap_days_before_payday INTEGER NOT NULL,
    asset_symbol VARCHAR(20) NOT NULL,
    asset_decimals INTEGER NOT NULL,
    reference_krw_per_asset NUMERIC(12, 2) NOT NULL,
    max_cap_display_krw_amount BIGINT NOT NULL,
    near_payday_max_cap_display_krw_amount BIGINT NOT NULL,
    fee_type VARCHAR(20) NOT NULL,
    flat_fee_display_krw_amount BIGINT NOT NULL,
    settlement_mode VARCHAR(40) NOT NULL,
    manual_repayment_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    disclaimer TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_advance_policies_enabled
    ON advance_policies (enabled, advance_policy_id DESC);
