-- DonDone Flyway baseline aligned to current backend code on 2026-03-17.
-- This file becomes the migration-owned source of truth for the initial backend schema.

CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE workplaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    map_label VARCHAR(100),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    allowed_radius_meters INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_workplaces_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_workplaces_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_workplaces_allowed_radius_meters CHECK (
        allowed_radius_meters IS NULL OR allowed_radius_meters > 0
    )
);

CREATE INDEX idx_workplaces_user_created_at
    ON workplaces (user_id, created_at DESC, id DESC);

CREATE TABLE work_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workplace_id BIGINT NOT NULL REFERENCES workplaces (id),
    pay_unit VARCHAR(20) NOT NULL,
    base_pay_amount NUMERIC(19, 2) NOT NULL,
    daily_work_minutes INTEGER,
    monthly_work_minutes INTEGER,
    normalized_hourly_wage NUMERIC(19, 2) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_work_contracts_pay_unit CHECK (pay_unit IN ('HOURLY', 'DAILY', 'MONTHLY')),
    CONSTRAINT ck_work_contracts_base_pay_amount CHECK (base_pay_amount > 0),
    CONSTRAINT ck_work_contracts_normalized_hourly_wage CHECK (normalized_hourly_wage > 0),
    CONSTRAINT ck_work_contracts_daily_work_minutes CHECK (
        daily_work_minutes IS NULL OR daily_work_minutes > 0
    ),
    CONSTRAINT ck_work_contracts_monthly_work_minutes CHECK (
        monthly_work_minutes IS NULL OR monthly_work_minutes > 0
    ),
    CONSTRAINT ck_work_contracts_unit_payload CHECK (
        (pay_unit = 'HOURLY' AND daily_work_minutes IS NULL AND monthly_work_minutes IS NULL)
        OR (pay_unit = 'DAILY' AND daily_work_minutes IS NOT NULL AND monthly_work_minutes IS NULL)
        OR (pay_unit = 'MONTHLY' AND monthly_work_minutes IS NOT NULL)
    ),
    CONSTRAINT ck_work_contracts_date_range CHECK (
        effective_to IS NULL OR effective_to >= effective_from
    )
);

CREATE UNIQUE INDEX uk_work_contracts_active_per_workplace
    ON work_contracts (workplace_id)
    WHERE effective_to IS NULL;

CREATE INDEX idx_work_contracts_workplace_effective_from
    ON work_contracts (workplace_id, effective_from DESC, id DESC);

ALTER TABLE work_contracts
    ADD CONSTRAINT ex_work_contracts_no_overlap
    EXCLUDE USING gist (
        workplace_id WITH =,
        daterange(effective_from, COALESCE(effective_to + 1, 'infinity'::date), '[)') WITH &&
    );

CREATE TABLE work_proofs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    workplace_id BIGINT REFERENCES workplaces (id),
    contract_id BIGINT REFERENCES work_contracts (id),
    work_date DATE NOT NULL,
    clock_in_at TIMESTAMP NOT NULL,
    clock_out_at TIMESTAMP,
    device_clock_in_at TIMESTAMP NOT NULL,
    device_clock_out_at TIMESTAMP,
    server_clock_in_at TIMESTAMP NOT NULL,
    server_clock_out_at TIMESTAMP,
    clock_in_latitude DOUBLE PRECISION NOT NULL,
    clock_in_longitude DOUBLE PRECISION NOT NULL,
    clock_out_latitude DOUBLE PRECISION,
    clock_out_longitude DOUBLE PRECISION,
    clock_in_location_label VARCHAR(100),
    clock_out_location_label VARCHAR(100),
    clock_out_outside_allowed_radius BOOLEAN,
    memo VARCHAR(500),
    edit_reason VARCHAR(500),
    attachment_count INTEGER NOT NULL DEFAULT 0,
    attachment_metadata_json TEXT,
    financial_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_work_proofs_work_date CHECK (
        work_date = clock_in_at::date
    ),
    CONSTRAINT ck_work_proofs_contract_pair CHECK (
        (workplace_id IS NULL AND contract_id IS NULL)
        OR (workplace_id IS NOT NULL AND contract_id IS NOT NULL)
    ),
    CONSTRAINT ck_work_proofs_clock_out_order CHECK (
        clock_out_at IS NULL OR clock_out_at > clock_in_at
    ),
    CONSTRAINT ck_work_proofs_device_clock_out_order CHECK (
        device_clock_out_at IS NULL OR device_clock_out_at > device_clock_in_at
    ),
    CONSTRAINT ck_work_proofs_server_clock_out_order CHECK (
        server_clock_out_at IS NULL OR server_clock_out_at >= server_clock_in_at
    ),
    CONSTRAINT ck_work_proofs_clock_out_payload CHECK (
        (
            clock_out_at IS NULL
            AND device_clock_out_at IS NULL
            AND server_clock_out_at IS NULL
            AND clock_out_latitude IS NULL
            AND clock_out_longitude IS NULL
        )
        OR (
            clock_out_at IS NOT NULL
            AND device_clock_out_at IS NOT NULL
            AND server_clock_out_at IS NOT NULL
            AND clock_out_latitude IS NOT NULL
            AND clock_out_longitude IS NOT NULL
        )
    ),
    CONSTRAINT ck_work_proofs_checkout_review_payload CHECK (
        clock_out_outside_allowed_radius IS NULL OR clock_out_at IS NOT NULL
    ),
    CONSTRAINT ck_work_proofs_attachment_count CHECK (attachment_count >= 0),
    CONSTRAINT ck_work_proofs_attachment_metadata_json CHECK (
        attachment_metadata_json IS NULL
        OR jsonb_typeof(attachment_metadata_json::jsonb) = 'array'
    ),
    CONSTRAINT ck_work_proofs_financial_status CHECK (
        financial_status IN ('PENDING', 'NEEDS_REVIEW', 'REFLECTED')
    ),
    CONSTRAINT ck_work_proofs_financial_status_payload CHECK (
        (financial_status = 'PENDING' AND clock_out_at IS NULL)
        OR (financial_status = 'REFLECTED' AND clock_out_at IS NOT NULL)
        OR (
            financial_status = 'NEEDS_REVIEW'
            AND clock_out_at IS NOT NULL
            AND clock_out_outside_allowed_radius IS TRUE
        )
    ),
    CONSTRAINT ck_work_proofs_clock_in_latitude CHECK (
        clock_in_latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT ck_work_proofs_clock_in_longitude CHECK (
        clock_in_longitude BETWEEN -180 AND 180
    ),
    CONSTRAINT ck_work_proofs_clock_out_latitude CHECK (
        clock_out_latitude IS NULL OR clock_out_latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT ck_work_proofs_clock_out_longitude CHECK (
        clock_out_longitude IS NULL OR clock_out_longitude BETWEEN -180 AND 180
    )
);

CREATE INDEX idx_work_proofs_user_work_date_clock_in
    ON work_proofs (user_id, work_date DESC, clock_in_at DESC, id DESC);

CREATE INDEX idx_work_proofs_user_workplace_work_date_clock_in
    ON work_proofs (user_id, workplace_id, work_date DESC, clock_in_at DESC, id DESC)
    WHERE workplace_id IS NOT NULL;

CREATE INDEX idx_work_proofs_user_open_created_at
    ON work_proofs (user_id, created_at DESC, id DESC)
    WHERE clock_out_at IS NULL;

CREATE TABLE work_proof_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_proof_id BIGINT NOT NULL REFERENCES work_proofs (id) ON DELETE CASCADE,
    actor_user_id BIGINT NOT NULL REFERENCES users (id),
    before_clock_in_at TIMESTAMP NOT NULL,
    before_clock_out_at TIMESTAMP NOT NULL,
    after_clock_in_at TIMESTAMP NOT NULL,
    after_clock_out_at TIMESTAMP NOT NULL,
    before_edit_reason VARCHAR(500),
    after_edit_reason VARCHAR(500) NOT NULL,
    before_memo VARCHAR(500),
    after_memo VARCHAR(500),
    before_attachment_count INTEGER NOT NULL,
    after_attachment_count INTEGER NOT NULL,
    before_attachment_metadata_json TEXT,
    after_attachment_metadata_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_work_proof_audit_logs_before_range CHECK (
        before_clock_out_at > before_clock_in_at
    ),
    CONSTRAINT ck_work_proof_audit_logs_after_range CHECK (
        after_clock_out_at > after_clock_in_at
    ),
    CONSTRAINT ck_work_proof_audit_logs_attachment_counts CHECK (
        before_attachment_count >= 0 AND after_attachment_count >= 0
    ),
    CONSTRAINT ck_work_proof_audit_logs_before_attachment_json CHECK (
        before_attachment_metadata_json IS NULL
        OR jsonb_typeof(before_attachment_metadata_json::jsonb) = 'array'
    ),
    CONSTRAINT ck_work_proof_audit_logs_after_attachment_json CHECK (
        after_attachment_metadata_json IS NULL
        OR jsonb_typeof(after_attachment_metadata_json::jsonb) = 'array'
    )
);

CREATE INDEX idx_work_proof_audit_logs_work_proof_created_at
    ON work_proof_audit_logs (work_proof_id, created_at DESC, id DESC);

CREATE TABLE wage_deposits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    year_month VARCHAR(7) NOT NULL,
    deposit_date DATE NOT NULL,
    actual_deposit_amount BIGINT NOT NULL,
    deductions_known BOOLEAN NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_wage_deposits_year_month CHECK (
        year_month ~ '^\d{4}-(0[1-9]|1[0-2])$'
    ),
    CONSTRAINT ck_wage_deposits_deposit_date_month CHECK (
        to_char(deposit_date, 'YYYY-MM') = year_month
    ),
    CONSTRAINT ck_wage_deposits_actual_deposit_amount CHECK (
        actual_deposit_amount >= 0
    )
);

CREATE INDEX idx_wage_deposits_user_year_month_deposit_date
    ON wage_deposits (user_id, year_month, deposit_date DESC, created_at DESC, id DESC);

CREATE TABLE wage_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    year_month VARCHAR(7) NOT NULL,
    workplace_id BIGINT NOT NULL REFERENCES workplaces (id),
    overtime_minutes BIGINT NOT NULL,
    night_minutes BIGINT NOT NULL,
    modified_record_count INTEGER NOT NULL,
    actual_deposit_amount BIGINT NOT NULL,
    deductions_known BOOLEAN NOT NULL,
    memo VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    resolution_stage VARCHAR(50) NOT NULL,
    base_estimate BIGINT NOT NULL,
    overtime_premium BIGINT NOT NULL,
    night_premium BIGINT NOT NULL,
    estimated_total BIGINT NOT NULL,
    difference_amount BIGINT NOT NULL,
    difference_rate NUMERIC(10, 4) NOT NULL,
    threshold_absolute_won BIGINT NOT NULL,
    threshold_relative_percent NUMERIC(10, 4) NOT NULL,
    threshold_deduction_relaxed BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_wage_verifications_year_month CHECK (
        year_month ~ '^\d{4}-(0[1-9]|1[0-2])$'
    ),
    CONSTRAINT ck_wage_verifications_status CHECK (
        status IN ('MATCHED', 'CHECK_REQUIRED')
    ),
    CONSTRAINT ck_wage_verifications_resolution_stage CHECK (
        resolution_stage IN (
            'SELF_CHECK',
            'EMPLOYER_CONFIRMATION_RECOMMENDED',
            'EXTERNAL_HELP_PREPARATION'
        )
    ),
    CONSTRAINT ck_wage_verifications_amounts CHECK (
        actual_deposit_amount >= 0
        AND base_estimate >= 0
        AND overtime_premium >= 0
        AND night_premium >= 0
        AND estimated_total >= 0
        AND threshold_absolute_won >= 0
    ),
    CONSTRAINT ck_wage_verifications_minutes_and_counts CHECK (
        overtime_minutes >= 0
        AND night_minutes >= 0
        AND modified_record_count >= 0
    ),
    CONSTRAINT ck_wage_verifications_difference_rate CHECK (
        difference_rate >= 0
    ),
    CONSTRAINT ck_wage_verifications_threshold_relative_percent CHECK (
        threshold_relative_percent >= 0 AND threshold_relative_percent <= 1
    )
);

CREATE INDEX idx_wage_verifications_user_created_at
    ON wage_verifications (user_id, created_at DESC, id DESC);

CREATE INDEX idx_wage_verifications_user_year_month_created_at
    ON wage_verifications (user_id, year_month, created_at DESC, id DESC);

CREATE TABLE wage_verification_record_ids (
    verification_id BIGINT NOT NULL REFERENCES wage_verifications (id) ON DELETE CASCADE,
    record_order INTEGER NOT NULL,
    record_id BIGINT NOT NULL REFERENCES work_proofs (id),
    PRIMARY KEY (verification_id, record_order),
    CONSTRAINT uk_wage_verification_record_ids_record UNIQUE (verification_id, record_id),
    CONSTRAINT ck_wage_verification_record_ids_record_order CHECK (record_order >= 0),
    CONSTRAINT ck_wage_verification_record_ids_record_id CHECK (record_id > 0)
);

CREATE INDEX idx_wage_verification_record_ids_record_id
    ON wage_verification_record_ids (record_id);

CREATE TABLE wage_verification_possible_causes (
    verification_id BIGINT NOT NULL REFERENCES wage_verifications (id) ON DELETE CASCADE,
    cause_order INTEGER NOT NULL,
    cause_code VARCHAR(100) NOT NULL,
    cause_title VARCHAR(200) NOT NULL,
    cause_detail VARCHAR(500) NOT NULL,
    PRIMARY KEY (verification_id, cause_order),
    CONSTRAINT ck_wage_verification_possible_causes_order CHECK (cause_order >= 0)
);

CREATE TABLE advance_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    workplace_id BIGINT NOT NULL REFERENCES workplaces (id),
    contract_id BIGINT NOT NULL REFERENCES work_contracts (id),
    year_month VARCHAR(7) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    requested_amount BIGINT NOT NULL,
    approved_amount BIGINT NOT NULL,
    fee_amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    repayment_due_date DATE NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    snapshot_available_amount BIGINT NOT NULL,
    snapshot_max_cap BIGINT NOT NULL,
    snapshot_policy_rate NUMERIC(5, 2) NOT NULL,
    snapshot_reflected_work_days INTEGER NOT NULL,
    snapshot_reflected_work_minutes BIGINT NOT NULL,
    snapshot_needs_review_record_count INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_advance_requests_user_idempotency UNIQUE (user_id, idempotency_key),
    CONSTRAINT ck_advance_requests_year_month CHECK (
        year_month ~ '^\d{4}-(0[1-9]|1[0-2])$'
    ),
    CONSTRAINT ck_advance_requests_status CHECK (
        status IN ('SUBMITTED', 'APPROVED', 'REJECTED', 'NEEDS_REVIEW')
    ),
    CONSTRAINT ck_advance_requests_amounts CHECK (
        requested_amount > 0
        AND approved_amount >= 0
        AND approved_amount <= requested_amount
        AND fee_amount >= 0
        AND snapshot_available_amount >= 0
        AND snapshot_max_cap >= 0
    ),
    CONSTRAINT ck_advance_requests_snapshot_policy_rate CHECK (
        snapshot_policy_rate >= 0 AND snapshot_policy_rate <= 1
    ),
    CONSTRAINT ck_advance_requests_snapshot_counts CHECK (
        snapshot_reflected_work_days >= 0
        AND snapshot_reflected_work_minutes >= 0
        AND snapshot_needs_review_record_count >= 0
    ),
    CONSTRAINT ck_advance_requests_repayment_due_date CHECK (
        repayment_due_date >= requested_at::date
    )
);

CREATE UNIQUE INDEX uk_advance_requests_approved_month
    ON advance_requests (user_id, workplace_id, year_month)
    WHERE status = 'APPROVED';

CREATE INDEX idx_advance_requests_user_year_month_requested_at
    ON advance_requests (user_id, year_month, requested_at DESC, created_at DESC, id DESC);

CREATE TABLE document_generation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(36) NOT NULL DEFAULT gen_random_uuid()::text,
    user_id BIGINT NOT NULL REFERENCES users (id),
    document_type VARCHAR(30) NOT NULL,
    wage_verification_id BIGINT NOT NULL REFERENCES wage_verifications (id),
    year_month VARCHAR(7) NOT NULL,
    workplace_id BIGINT NOT NULL REFERENCES workplaces (id),
    output_format VARCHAR(10) NOT NULL,
    include_attachments BOOLEAN NOT NULL DEFAULT FALSE,
    idempotency_key VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_document_generation_requests_request_id UNIQUE (request_id),
    CONSTRAINT uk_document_generation_requests_user_type_key UNIQUE (user_id, document_type, idempotency_key),
    CONSTRAINT ck_document_generation_requests_request_id CHECK (
        request_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ),
    CONSTRAINT ck_document_generation_requests_document_type CHECK (
        document_type IN ('PROOF_PACK', 'CLAIM_KIT', 'TRANSFER_RECEIPT')
    ),
    CONSTRAINT ck_document_generation_requests_year_month CHECK (
        year_month ~ '^\d{4}-(0[1-9]|1[0-2])$'
    ),
    CONSTRAINT ck_document_generation_requests_output_format CHECK (
        output_format IN ('PDF', 'ZIP')
    ),
    CONSTRAINT ck_document_generation_requests_status CHECK (
        status IN ('QUEUED', 'RUNNING', 'READY', 'FAILED')
    )
);

CREATE INDEX idx_document_generation_requests_user_type_created_at
    ON document_generation_requests (user_id, document_type, created_at DESC, id DESC);

CREATE INDEX idx_document_generation_requests_verification_created_at
    ON document_generation_requests (wage_verification_id, created_at DESC, id DESC);

CREATE TABLE claim_preparations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    wage_verification_id BIGINT NOT NULL REFERENCES wage_verifications (id),
    claim_kit_document_id BIGINT REFERENCES document_generation_requests (id),
    locale VARCHAR(20) NOT NULL,
    tone VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    summary_text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_claim_preparations_tone CHECK (
        tone IN ('DEFAULT', 'POLITE', 'SHORT')
    ),
    CONSTRAINT ck_claim_preparations_status CHECK (
        status IN ('READY')
    )
);

CREATE INDEX idx_claim_preparations_user_created_at
    ON claim_preparations (user_id, created_at DESC, id DESC);

CREATE INDEX idx_claim_preparations_verification_created_at
    ON claim_preparations (wage_verification_id, created_at DESC, id DESC);

CREATE TRIGGER trg_users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_workplaces_set_updated_at
    BEFORE UPDATE ON workplaces
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_work_contracts_set_updated_at
    BEFORE UPDATE ON work_contracts
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_work_proofs_set_updated_at
    BEFORE UPDATE ON work_proofs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_wage_deposits_set_updated_at
    BEFORE UPDATE ON wage_deposits
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_wage_verifications_set_updated_at
    BEFORE UPDATE ON wage_verifications
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_document_generation_requests_set_updated_at
    BEFORE UPDATE ON document_generation_requests
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
